# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreifaltigkeithomepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='event_type',
            field=models.CharField(blank=True, choices=[('default', 'Sonstige Veranstaltung')], max_length=255, null=True, verbose_name='Veranstaltungstyp'),
        ),
    ]
